/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import controller.PessoaGerenciamento;
import model.dao.*;
import model.rn.PessoaRN;
import model.vo.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joaop
 */
public class JPPesGerenciamento extends javax.swing.JPanel {
    private final PessoaGerenciamento controller = new PessoaGerenciamento();


    /**
     * Creates new form NewJPanel
     */
    public JPPesGerenciamento() throws SQLException {
        initComponents();
        carregarEstados();
        carregarCidades();
        carregarSexo();
        carregarBairro();
        carregarLogradouro();
        campos(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBtnNovaPes = new javax.swing.JPanel();
        jBtnNovaPessoa = new javax.swing.JButton();
        jPInfoPes = new javax.swing.JPanel();
        jLNomePes = new javax.swing.JLabel();
        jTNomePes = new javax.swing.JTextField();
        jLPesCpf = new javax.swing.JLabel();
        jLPesDtNascimento = new javax.swing.JLabel();
        jLPesEmail = new javax.swing.JLabel();
        jLPesSexo = new javax.swing.JLabel();
        jTPesCpf = new javax.swing.JTextField();
        jTPesEmail = new javax.swing.JTextField();
        jLPesTelefone = new javax.swing.JLabel();
        jLTelCodPais = new javax.swing.JLabel();
        jLTelDDD = new javax.swing.JLabel();
        jLTelNumero = new javax.swing.JLabel();
        jTTelCodPais = new javax.swing.JTextField();
        jTTelDDD = new javax.swing.JTextField();
        jTTelNumero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jCbPesSexo = new javax.swing.JComboBox<>();
        jPInfoEnd = new javax.swing.JPanel();
        jLEndEstado = new javax.swing.JLabel();
        jLEndCidade = new javax.swing.JLabel();
        jLEndBairro = new javax.swing.JLabel();
        jCbEstado = new javax.swing.JComboBox<>();
        jCbCidade = new javax.swing.JComboBox<>();
        jCbEndBairro = new javax.swing.JComboBox<>();
        jLEndLogradouro = new javax.swing.JLabel();
        jCbEndLogradouro = new javax.swing.JComboBox<>();
        jLEndCep = new javax.swing.JLabel();
        jTEndCep = new javax.swing.JTextField();
        jLEndNomeRua = new javax.swing.JLabel();
        jTEndNomeRua = new javax.swing.JTextField();
        jLEndComplemento = new javax.swing.JLabel();
        jLEndNumero = new javax.swing.JLabel();
        jTEndNumero = new javax.swing.JTextField();
        jTEndComplemento = new javax.swing.JTextField();
        jPAttPes = new javax.swing.JPanel();
        jBtnAttPes = new javax.swing.JButton();
        jPDelPes = new javax.swing.JPanel();
        jBtnDeletarPes = new javax.swing.JButton();
        jPBtnFecharJnPes = new javax.swing.JPanel();
        jBtnFecharPes = new javax.swing.JButton();
        jPBusca = new javax.swing.JPanel();
        jTBusca = new javax.swing.JTextField();
        jCbPesTipoBusca = new javax.swing.JComboBox<>();
        jBtnPesBuscar = new javax.swing.JButton();
        jPBtnSalvar = new javax.swing.JPanel();
        jBtnSalvarPes = new javax.swing.JButton();

        jPBtnNovaPes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnNovaPessoa.setText("Novo");

        javax.swing.GroupLayout jPBtnNovaPesLayout = new javax.swing.GroupLayout(jPBtnNovaPes);
        jPBtnNovaPes.setLayout(jPBtnNovaPesLayout);
        jPBtnNovaPesLayout.setHorizontalGroup(
            jPBtnNovaPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnNovaPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNovaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnNovaPesLayout.setVerticalGroup(
            jPBtnNovaPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnNovaPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNovaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPInfoPes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLNomePes.setText("Nome:");

        jTNomePes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomePesActionPerformed(evt);
            }
        });

        jLPesCpf.setText("CPF:");

        jLPesDtNascimento.setText("Data Nascimento:");

        jLPesEmail.setText("Email:");

        jLPesSexo.setText("Sexo:");

        jLPesTelefone.setText("Telefone:");

        jLTelCodPais.setText("Codifo Pais:");

        jLTelDDD.setText("DDD:");

        jLTelNumero.setText("Numero:");

        jCbPesSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPInfoPesLayout = new javax.swing.GroupLayout(jPInfoPes);
        jPInfoPes.setLayout(jPInfoPesLayout);
        jPInfoPesLayout.setHorizontalGroup(
            jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoPesLayout.createSequentialGroup()
                        .addComponent(jLNomePes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNomePes))
                    .addGroup(jPInfoPesLayout.createSequentialGroup()
                        .addComponent(jLPesCpf)
                        .addGap(18, 18, 18)
                        .addComponent(jTPesCpf))
                    .addGroup(jPInfoPesLayout.createSequentialGroup()
                        .addComponent(jLPesEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPesEmail))
                    .addGroup(jPInfoPesLayout.createSequentialGroup()
                        .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPInfoPesLayout.createSequentialGroup()
                                .addComponent(jLPesSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jCbPesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLPesDtNascimento)
                            .addComponent(jLPesTelefone)
                            .addGroup(jPInfoPesLayout.createSequentialGroup()
                                .addComponent(jLTelDDD)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelDDD))
                            .addGroup(jPInfoPesLayout.createSequentialGroup()
                                .addComponent(jLTelNumero)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelNumero))
                            .addGroup(jPInfoPesLayout.createSequentialGroup()
                                .addComponent(jLTelCodPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTTelCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPInfoPesLayout.setVerticalGroup(
            jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoPesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomePes)
                    .addComponent(jTNomePes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesCpf)
                    .addComponent(jTPesCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLPesDtNascimento)
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesEmail)
                    .addComponent(jTPesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesSexo)
                    .addComponent(jCbPesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLPesTelefone)
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelCodPais)
                    .addComponent(jTTelCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelDDD)
                    .addComponent(jTTelDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelNumero)
                    .addComponent(jTTelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPInfoEnd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLEndEstado.setText("Estado:");

        jLEndCidade.setText("Cidade:");

        jLEndBairro.setText("Bairro:");

        jCbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCbEndBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLEndLogradouro.setText("Logradouro:");

        jCbEndLogradouro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLEndCep.setText("CEP:");

        jTEndCep.setText("Informe o CEP");

        jLEndNomeRua.setText("Nome Rua/Avenida:");

        jTEndNomeRua.setText("Informe o nome da rua/avenida");

        jLEndComplemento.setText("Complemento:");

        jLEndNumero.setText("Numero:");

        jTEndNumero.setText("Informe o numero");

        jTEndComplemento.setText("Informe o complemento");

        javax.swing.GroupLayout jPInfoEndLayout = new javax.swing.GroupLayout(jPInfoEnd);
        jPInfoEnd.setLayout(jPInfoEndLayout);
        jPInfoEndLayout.setHorizontalGroup(
            jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfoEndLayout.createSequentialGroup()
                        .addComponent(jLEndNomeRua)
                        .addGap(18, 18, 18)
                        .addComponent(jTEndNomeRua, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                    .addGroup(jPInfoEndLayout.createSequentialGroup()
                        .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInfoEndLayout.createSequentialGroup()
                                .addComponent(jLEndEstado)
                                .addGap(18, 18, 18)
                                .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInfoEndLayout.createSequentialGroup()
                                .addComponent(jLEndBairro)
                                .addGap(18, 18, 18)
                                .addComponent(jCbEndBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInfoEndLayout.createSequentialGroup()
                                .addComponent(jLEndLogradouro)
                                .addGap(18, 18, 18)
                                .addComponent(jCbEndLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPInfoEndLayout.createSequentialGroup()
                                    .addComponent(jLEndCep)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTEndCep))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPInfoEndLayout.createSequentialGroup()
                                    .addComponent(jLEndCidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPInfoEndLayout.createSequentialGroup()
                        .addComponent(jLEndComplemento)
                        .addGap(18, 18, 18)
                        .addComponent(jTEndComplemento))
                    .addGroup(jPInfoEndLayout.createSequentialGroup()
                        .addComponent(jLEndNumero)
                        .addGap(18, 18, 18)
                        .addComponent(jTEndNumero)))
                .addContainerGap())
        );
        jPInfoEndLayout.setVerticalGroup(
            jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndEstado)
                    .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndCidade)
                    .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndCep)
                    .addComponent(jTEndCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndNomeRua)
                    .addComponent(jTEndNomeRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndBairro)
                    .addComponent(jCbEndBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndLogradouro)
                    .addComponent(jCbEndLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndNumero)
                    .addComponent(jTEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPInfoEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndComplemento)
                    .addComponent(jTEndComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPAttPes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnAttPes.setText("Atualizar");

        javax.swing.GroupLayout jPAttPesLayout = new javax.swing.GroupLayout(jPAttPes);
        jPAttPes.setLayout(jPAttPesLayout);
        jPAttPesLayout.setHorizontalGroup(
            jPAttPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAttPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAttPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPAttPesLayout.setVerticalGroup(
            jPAttPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAttPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAttPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPDelPes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnDeletarPes.setText("Deletar");

        javax.swing.GroupLayout jPDelPesLayout = new javax.swing.GroupLayout(jPDelPes);
        jPDelPes.setLayout(jPDelPesLayout);
        jPDelPesLayout.setHorizontalGroup(
            jPDelPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDelPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnDeletarPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPDelPesLayout.setVerticalGroup(
            jPDelPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDelPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnDeletarPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnFecharJnPes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFecharPes.setText("Fechar");

        javax.swing.GroupLayout jPBtnFecharJnPesLayout = new javax.swing.GroupLayout(jPBtnFecharJnPes);
        jPBtnFecharJnPes.setLayout(jPBtnFecharJnPesLayout);
        jPBtnFecharJnPesLayout.setHorizontalGroup(
            jPBtnFecharJnPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnFecharJnPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFecharPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnFecharJnPesLayout.setVerticalGroup(
            jPBtnFecharJnPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnFecharJnPesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFecharPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTBusca.setText("Selecione o tipo de busca");

        jCbPesTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por CPF", "Busca por Nome" }));

        jBtnPesBuscar.setText("Buscar");

        javax.swing.GroupLayout jPBuscaLayout = new javax.swing.GroupLayout(jPBusca);
        jPBusca.setLayout(jPBuscaLayout);
        jPBuscaLayout.setHorizontalGroup(
            jPBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbPesTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPesBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBuscaLayout.setVerticalGroup(
            jPBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbPesTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBtnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnSalvarPes.setText("Salvar");

        javax.swing.GroupLayout jPBtnSalvarLayout = new javax.swing.GroupLayout(jPBtnSalvar);
        jPBtnSalvar.setLayout(jPBtnSalvarLayout);
        jPBtnSalvarLayout.setHorizontalGroup(
            jPBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnSalvarPes, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnSalvarLayout.setVerticalGroup(
            jPBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnSalvarPes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPBtnNovaPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPAttPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPDelPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBtnFecharJnPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPInfoPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPInfoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDelPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPBtnNovaPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPAttPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPBtnFecharJnPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPInfoPes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPInfoEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomePesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomePesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomePesActionPerformed

    private void jBtnNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{
        campos(true);
    }

    private void setjBtnSalvarPesActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{
        jBtnSalvarPes.addActionListener(e -> {
            try {
                addPessoa();
            } catch (SQLException ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro de SQL: " + ex.getMessage());
            }
        });
        addPessoa();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAttPes;
    private javax.swing.JButton jBtnDeletarPes;
    private javax.swing.JButton jBtnFecharPes;
    private javax.swing.JButton jBtnNovaPessoa;
    private javax.swing.JButton jBtnPesBuscar;
    private javax.swing.JButton jBtnSalvarPes;
    private javax.swing.JComboBox<String> jCbCidade;
    private javax.swing.JComboBox<String> jCbEndBairro;
    private javax.swing.JComboBox<String> jCbEndLogradouro;
    private javax.swing.JComboBox<String> jCbEstado;
    private javax.swing.JComboBox<String> jCbPesSexo;
    private javax.swing.JComboBox<String> jCbPesTipoBusca;
    private javax.swing.JLabel jLEndBairro;
    private javax.swing.JLabel jLEndCep;
    private javax.swing.JLabel jLEndCidade;
    private javax.swing.JLabel jLEndComplemento;
    private javax.swing.JLabel jLEndEstado;
    private javax.swing.JLabel jLEndLogradouro;
    private javax.swing.JLabel jLEndNomeRua;
    private javax.swing.JLabel jLEndNumero;
    private javax.swing.JLabel jLNomePes;
    private javax.swing.JLabel jLPesCpf;
    private javax.swing.JLabel jLPesDtNascimento;
    private javax.swing.JLabel jLPesEmail;
    private javax.swing.JLabel jLPesSexo;
    private javax.swing.JLabel jLPesTelefone;
    private javax.swing.JLabel jLTelCodPais;
    private javax.swing.JLabel jLTelDDD;
    private javax.swing.JLabel jLTelNumero;
    private javax.swing.JPanel jPAttPes;
    private javax.swing.JPanel jPBtnFecharJnPes;
    private javax.swing.JPanel jPBtnNovaPes;
    private javax.swing.JPanel jPBtnSalvar;
    private javax.swing.JPanel jPBusca;
    private javax.swing.JPanel jPDelPes;
    private javax.swing.JPanel jPInfoEnd;
    private javax.swing.JPanel jPInfoPes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTBusca;
    private javax.swing.JTextField jTEndCep;
    private javax.swing.JTextField jTEndComplemento;
    private javax.swing.JTextField jTEndNomeRua;
    private javax.swing.JTextField jTEndNumero;
    private javax.swing.JTextField jTNomePes;
    private javax.swing.JTextField jTPesCpf;
    private javax.swing.JTextField jTPesEmail;
    private javax.swing.JTextField jTTelCodPais;
    private javax.swing.JTextField jTTelDDD;
    private javax.swing.JTextField jTTelNumero;
    // End of variables declaration//GEN-END:variables

    private void campos(boolean estado){
        jTNomePes.setEditable(estado);
        jTPesCpf.setEditable(estado);
        jTPesEmail.setEditable(estado);
        jTTelCodPais.setEditable(estado);
        jTTelDDD.setEditable(estado);
        jTTelNumero.setEditable(estado);
        jTEndCep.setEditable(estado);
        jTEndNomeRua.setEditable(estado);
        jTEndNumero.setEditable(estado);
        jTEndComplemento.setEditable(estado);
    }

    private void limparCampos(){
        jTNomePes.setText("");
        jTPesCpf.setText("");
        jTPesEmail.setText("");
        jTTelCodPais.setText("");
        jTTelDDD.setText("");
        jTTelNumero.setText("");
        jTEndCep.setText("");
        jTEndNomeRua.setText("");
        jTEndNumero.setText("");
        jTEndComplemento.setText("");
    }

    private void carregarEstados() throws SQLException{
        EstadoDAO estDao = new EstadoDAO();
        try {
            List<EstadoVO> estados = estDao.buscarTodosEstados();
            for (EstadoVO e : estados){
                jCbEstado.addItem(String.valueOf(e));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro ao carregar itens" + e);
        }
    }

    private void carregarCidades() throws SQLException{
        CidadeDAO cidDao = new CidadeDAO();
        try {
            List<CidadeVO> cidades = cidDao.buscarTodasCidades();
            for (CidadeVO cid : cidades){
                jCbCidade.addItem(String.valueOf(cid));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro ao carregar itens" + e);
        }

    }

    private void carregarSexo() throws SQLException{
        SexoDAO sexoDAO = new SexoDAO();
        try {
            List<SexoVO> sexo = sexoDAO.buscarTodosSexo();
            for (SexoVO sex : sexo){
                jCbPesSexo.addItem(String.valueOf(sex));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro ao carregar itens" + e);
        }
    }

    private void carregarBairro() throws SQLException{
        BairroDAO bairroDAO = new BairroDAO();
        try {
            List<BairroVO> bairros = bairroDAO.buscarTodosBairros();
            for (BairroVO bairro : bairros){
                jCbEndBairro.addItem(String.valueOf(bairro));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro ao carregar itens" + e);
        }
    }

    private void carregarLogradouro() throws SQLException{
        LogradouroDAO logradouroDAO = new LogradouroDAO();
        try {
            List<LogradouroVO> logradouros = logradouroDAO.buscarTodosLogradouros();
            for (LogradouroVO logradouro : logradouros){
                jCbEndLogradouro.addItem(String.valueOf(logradouro));
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro ao carregar itens" + e);
        }
    }


    private void addPessoa() throws SQLException{
        PessoaVO pes = new PessoaVO();

        pes.setPes_cpf(jTPesCpf.getText());
        pes.setPes_nome(jTNomePes.getText());

        // -- sexo --
        SexoVO sexSelecionado = (SexoVO) jCbPesSexo.getSelectedItem();
        if (sexSelecionado != null){
            System.out.println("ID: " + sexSelecionado.getSex_id());
            System.out.println("Descricao: " + sexSelecionado.getSex_descricao());
        }
        SexoVO s = new SexoVO();
        s.setSex_id(sexSelecionado.getSex_id());

        // -- cidades --
        CidadeVO cidSelecionada = (CidadeVO) jCbCidade.getSelectedItem();
        if (cidSelecionada != null){
            System.out.println("ID: " + cidSelecionada.getCid_id());
            System.out.println("Nome: " + cidSelecionada.getCid_descricao());
        }
        CidadeVO cid = new CidadeVO();
        cid.setCid_id(cidSelecionada.getCid_id());

        // -- estados --
        EstadoVO selecionado = (EstadoVO) jCbEstado.getSelectedItem();
        if (selecionado != null) {
            System.out.println("Sigla: " + selecionado.getEst_sigla());
            System.out.println("Nome: " + selecionado.getEst_descricao());
        }
        EstadoVO est = new EstadoVO();
        est.setEst_sigla(selecionado.getEst_sigla());

        // -- bairro --
        BairroVO bairroSelecionado = (BairroVO) jCbEndBairro.getSelectedItem();
        if (bairroSelecionado != null){
            System.out.println("ID: " + bairroSelecionado.getBairro_id());
            System.out.println("Nome: " + bairroSelecionado.getBairro_descricao());
        }
        BairroVO bairro = new BairroVO();
        bairro.setBairro_id(bairroSelecionado.getBairro_id());

        // -- logradouro --
        LogradouroVO logradouroSelecionado = (LogradouroVO) jCbEndBairro.getSelectedItem();
        if (logradouroSelecionado != null){
            System.out.println("ID: " + logradouroSelecionado.getLogradouro_id());
            System.out.println("Nome: " + logradouroSelecionado.getLogradouro_descricao());
        }
        LogradouroVO lograd = new LogradouroVO();
        lograd.setLogradouro_id(logradouroSelecionado.getLogradouro_id());

        EndPostalVO ep = new EndPostalVO();
        ep.setEndP_nomeRua(jTEndNomeRua.getText());
        ep.setEndP_cep(jTEndCep.getText());
        ep.setEndP_bairro(bairro);
        ep.setEndP_cidade(cid);
        ep.setEndP_estado(est);
        ep.setEndP_logradouro(lograd);

        EnderecoVO end = new EnderecoVO();
        end.setEnd_complemento(jTEndComplemento.getText());
        end.setEnd_numero(jTEndNumero.getText());
        end.setEnd_endP_id(ep);

        java.util.List<EnderecoVO> enderecos = new java.util.ArrayList<>();
        enderecos.add(end);
        pes.setEndereco(enderecos);

        TelefoneVO tel = new TelefoneVO();
        tel.setTel_codPais(jTTelCodPais.getText());
        tel.setTel_ddd(jTTelDDD.getText());
        tel.setTel_numero(jTTelNumero.getText());
        tel.setTel_pes_cpf(pes.getPes_cpf());

        pes.setPes_ativo(true);

        try {
            controller.cadastrarPessoa(pes);
            JOptionPane.showMessageDialog(null, "Pessoa cadastrada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar pessoa!");
            e.printStackTrace();
        }

    }


}
