/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author joaop
 */
public class JPFncGerenciamento extends javax.swing.JPanel {

    /**
     * Creates new form JPFncGerenciamento
     */
    public JPFncGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFncGenBtnAdd = new javax.swing.JPanel();
        jBtnFncGenAdd = new javax.swing.JButton();
        jPFncGenBtnAtt = new javax.swing.JPanel();
        jBtnFncGenAtt = new javax.swing.JButton();
        jPFncGenBtnDel = new javax.swing.JPanel();
        jBtnFncGenDel = new javax.swing.JButton();
        jPFncGenBtnSalvar = new javax.swing.JPanel();
        jBtnFncGenSalvar = new javax.swing.JButton();
        jPFncGenBtnFechar = new javax.swing.JPanel();
        jBtnFncGenFechar = new javax.swing.JButton();
        jPFncGenBusca = new javax.swing.JPanel();
        jCbFncGenTipoBusca = new javax.swing.JComboBox<>();
        jBtnFncGenBusca = new javax.swing.JButton();
        jTFncGenBusca = new javax.swing.JTextField();
        jPFncGenPesTel = new javax.swing.JPanel();
        jLFncGenPesNome = new javax.swing.JLabel();
        jLFncGenPesCPF = new javax.swing.JLabel();
        jLFncGenPesDtNascimento = new javax.swing.JLabel();
        jLFncGenPesEmail = new javax.swing.JLabel();
        jLFncGenPesSexo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLFncGenTelCodPais = new javax.swing.JLabel();
        jLFncTelGenDDD = new javax.swing.JLabel();
        jLFncTelGenTelNum = new javax.swing.JLabel();
        jTFncGenPesNome = new javax.swing.JTextField();
        jTFncGenPesCpf = new javax.swing.JTextField();
        jTFncGenPesEmail = new javax.swing.JTextField();
        jTFncGenTelCodPais = new javax.swing.JTextField();
        jTFncGenTelDDD = new javax.swing.JTextField();
        jTFncGenTelNumero = new javax.swing.JTextField();
        jCbFncGenPesSexo = new javax.swing.JComboBox<>();
        jPFncGenEndRH = new javax.swing.JPanel();
        jLFncGenContracao = new javax.swing.JLabel();
        jLFncGenSalario = new javax.swing.JLabel();
        jLFncGenCargo = new javax.swing.JLabel();
        jCbFncGenCargo = new javax.swing.JComboBox<>();
        jTFncGenSalario = new javax.swing.JTextField();
        jLFncGenEndEst = new javax.swing.JLabel();
        jCbFncGenEndEst = new javax.swing.JComboBox<>();
        jLFncGenEndCid = new javax.swing.JLabel();
        jCbFncGenEndCid = new javax.swing.JComboBox<>();
        jLFncGenEndCep = new javax.swing.JLabel();
        jTFncGenEndCep = new javax.swing.JTextField();
        jLFncGenEndLog = new javax.swing.JLabel();
        jCbFncGenEndLog = new javax.swing.JComboBox<>();
        jLFncGenEndRuaAv = new javax.swing.JLabel();
        jTFncGenEndRuaAv = new javax.swing.JTextField();
        jLFncGenEndBairro = new javax.swing.JLabel();
        jTFncGenEndBairro = new javax.swing.JTextField();
        jLFncGenEndNum = new javax.swing.JLabel();
        jTFncGenEndNumero = new javax.swing.JTextField();
        jLFncGenEndComplemento = new javax.swing.JLabel();
        jTFncGenEndComplemento = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLFncGenDtContracao = new javax.swing.JLabel();

        jPFncGenBtnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFncGenAdd.setText("Novo");

        javax.swing.GroupLayout jPFncGenBtnAddLayout = new javax.swing.GroupLayout(jPFncGenBtnAdd);
        jPFncGenBtnAdd.setLayout(jPFncGenBtnAddLayout);
        jPFncGenBtnAddLayout.setHorizontalGroup(
            jPFncGenBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFncGenBtnAddLayout.setVerticalGroup(
            jPFncGenBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPFncGenBtnAtt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFncGenAtt.setText("Atualizar");

        javax.swing.GroupLayout jPFncGenBtnAttLayout = new javax.swing.GroupLayout(jPFncGenBtnAtt);
        jPFncGenBtnAtt.setLayout(jPFncGenBtnAttLayout);
        jPFncGenBtnAttLayout.setHorizontalGroup(
            jPFncGenBtnAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnAttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenAtt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFncGenBtnAttLayout.setVerticalGroup(
            jPFncGenBtnAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnAttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenAtt, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPFncGenBtnDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFncGenDel.setText("Deletar");

        javax.swing.GroupLayout jPFncGenBtnDelLayout = new javax.swing.GroupLayout(jPFncGenBtnDel);
        jPFncGenBtnDel.setLayout(jPFncGenBtnDelLayout);
        jPFncGenBtnDelLayout.setHorizontalGroup(
            jPFncGenBtnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenDel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFncGenBtnDelLayout.setVerticalGroup(
            jPFncGenBtnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenDel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPFncGenBtnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFncGenSalvar.setText("Salvar");

        javax.swing.GroupLayout jPFncGenBtnSalvarLayout = new javax.swing.GroupLayout(jPFncGenBtnSalvar);
        jPFncGenBtnSalvar.setLayout(jPFncGenBtnSalvarLayout);
        jPFncGenBtnSalvarLayout.setHorizontalGroup(
            jPFncGenBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFncGenBtnSalvarLayout.setVerticalGroup(
            jPFncGenBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPFncGenBtnFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnFncGenFechar.setText("Fechar");

        javax.swing.GroupLayout jPFncGenBtnFecharLayout = new javax.swing.GroupLayout(jPFncGenBtnFechar);
        jPFncGenBtnFechar.setLayout(jPFncGenBtnFecharLayout);
        jPFncGenBtnFecharLayout.setHorizontalGroup(
            jPFncGenBtnFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBtnFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFncGenBtnFecharLayout.setVerticalGroup(
            jPFncGenBtnFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFncGenBtnFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFncGenFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPFncGenBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCbFncGenTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por Nome", "Busca por CPF" }));

        jBtnFncGenBusca.setText("Buscar");

        javax.swing.GroupLayout jPFncGenBuscaLayout = new javax.swing.GroupLayout(jPFncGenBusca);
        jPFncGenBusca.setLayout(jPFncGenBuscaLayout);
        jPFncGenBuscaLayout.setHorizontalGroup(
            jPFncGenBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbFncGenTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFncGenBusca)
                .addGap(18, 18, 18)
                .addComponent(jBtnFncGenBusca)
                .addContainerGap())
        );
        jPFncGenBuscaLayout.setVerticalGroup(
            jPFncGenBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFncGenBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbFncGenTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFncGenBusca)
                    .addComponent(jTFncGenBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPFncGenPesTel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLFncGenPesNome.setText("Nome:");

        jLFncGenPesCPF.setText("CPF:");

        jLFncGenPesDtNascimento.setText("Data Nascimento:");

        jLFncGenPesEmail.setText("Email:");

        jLFncGenPesSexo.setText("Sexo:");

        jLFncGenTelCodPais.setText("Codigo Pais:");

        jLFncTelGenDDD.setText("DDD:");

        jLFncTelGenTelNum.setText("Numero:");

        jTFncGenPesNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFncGenPesNomeActionPerformed(evt);
            }
        });

        jCbFncGenPesSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPFncGenPesTelLayout = new javax.swing.GroupLayout(jPFncGenPesTel);
        jPFncGenPesTel.setLayout(jPFncGenPesTelLayout);
        jPFncGenPesTelLayout.setHorizontalGroup(
            jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                        .addComponent(jLFncGenPesNome)
                        .addGap(18, 18, 18)
                        .addComponent(jTFncGenPesNome))
                    .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                        .addComponent(jLFncGenPesCPF)
                        .addGap(18, 18, 18)
                        .addComponent(jTFncGenPesCpf))
                    .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                        .addComponent(jLFncGenPesEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jTFncGenPesEmail))
                    .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                        .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                                .addComponent(jLFncGenPesSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jCbFncGenPesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                                    .addComponent(jLFncTelGenDDD)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFncGenTelDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                                    .addComponent(jLFncTelGenTelNum)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFncGenTelNumero))
                                .addComponent(jLFncGenPesDtNascimento)
                                .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                                    .addComponent(jLFncGenTelCodPais)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFncGenTelCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 299, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPFncGenPesTelLayout.setVerticalGroup(
            jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenPesTelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenPesNome)
                    .addComponent(jTFncGenPesNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenPesCPF)
                    .addComponent(jTFncGenPesCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLFncGenPesDtNascimento)
                .addGap(18, 18, 18)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenPesEmail)
                    .addComponent(jTFncGenPesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenPesSexo)
                    .addComponent(jCbFncGenPesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenTelCodPais)
                    .addComponent(jTFncGenTelCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncTelGenDDD)
                    .addComponent(jTFncGenTelDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenPesTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncTelGenTelNum)
                    .addComponent(jTFncGenTelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPFncGenEndRH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLFncGenContracao.setText("Contratacao");

        jLFncGenSalario.setText("Salario:");

        jLFncGenCargo.setText("Cargo:");

        jCbFncGenCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLFncGenEndEst.setText("Estado:");

        jCbFncGenEndEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLFncGenEndCid.setText("Cidade:");

        jCbFncGenEndCid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLFncGenEndCep.setText("CEP:");

        jLFncGenEndLog.setText("Logradouro:");

        jCbFncGenEndLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLFncGenEndRuaAv.setText("Nome Rua/Avenida:");

        jLFncGenEndBairro.setText("Bairro:");

        jLFncGenEndNum.setText("Numero:");

        jLFncGenEndComplemento.setText("Complemento:");

        jLFncGenDtContracao.setText("Data Contratacao:");

        javax.swing.GroupLayout jPFncGenEndRHLayout = new javax.swing.GroupLayout(jPFncGenEndRH);
        jPFncGenEndRH.setLayout(jPFncGenEndRHLayout);
        jPFncGenEndRHLayout.setHorizontalGroup(
            jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                        .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenEndBairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFncGenEndBairro))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenEndLog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCbFncGenEndLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenEndRuaAv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFncGenEndRuaAv))
                                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenEndNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFncGenEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                .addComponent(jLFncGenEndEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbFncGenEndEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLFncGenEndCid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbFncGenEndCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLFncGenEndCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFncGenEndCep, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenSalario)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFncGenSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                                        .addComponent(jLFncGenCargo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbFncGenCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLFncGenContracao))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                        .addComponent(jLFncGenEndComplemento)
                        .addGap(18, 18, 18)
                        .addComponent(jTFncGenEndComplemento)
                        .addContainerGap())
                    .addGroup(jPFncGenEndRHLayout.createSequentialGroup()
                        .addComponent(jLFncGenDtContracao)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPFncGenEndRHLayout.setVerticalGroup(
            jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFncGenEndRHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenEndEst)
                    .addComponent(jCbFncGenEndEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFncGenEndCid)
                    .addComponent(jCbFncGenEndCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFncGenEndCep)
                    .addComponent(jTFncGenEndCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFncGenEndLog)
                    .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCbFncGenEndLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLFncGenEndRuaAv)
                        .addComponent(jTFncGenEndRuaAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenEndBairro)
                    .addComponent(jTFncGenEndBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFncGenEndNum)
                    .addComponent(jTFncGenEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenEndComplemento)
                    .addComponent(jTFncGenEndComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLFncGenContracao)
                .addGap(18, 18, 18)
                .addComponent(jLFncGenDtContracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenSalario)
                    .addComponent(jTFncGenSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFncGenEndRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFncGenCargo)
                    .addComponent(jCbFncGenCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFncGenBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPFncGenBtnAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPFncGenBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPFncGenBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPFncGenBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFncGenBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPFncGenPesTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jPFncGenEndRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPFncGenBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFncGenBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFncGenBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFncGenBtnAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFncGenBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPFncGenBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPFncGenPesTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPFncGenEndRH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTFncGenPesNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFncGenPesNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFncGenPesNomeActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFncGenAdd;
    private javax.swing.JButton jBtnFncGenAtt;
    private javax.swing.JButton jBtnFncGenBusca;
    private javax.swing.JButton jBtnFncGenDel;
    private javax.swing.JButton jBtnFncGenFechar;
    private javax.swing.JButton jBtnFncGenSalvar;
    private javax.swing.JComboBox<String> jCbFncGenCargo;
    private javax.swing.JComboBox<String> jCbFncGenEndCid;
    private javax.swing.JComboBox<String> jCbFncGenEndEst;
    private javax.swing.JComboBox<String> jCbFncGenEndLog;
    private javax.swing.JComboBox<String> jCbFncGenPesSexo;
    private javax.swing.JComboBox<String> jCbFncGenTipoBusca;
    private javax.swing.JLabel jLFncGenCargo;
    private javax.swing.JLabel jLFncGenContracao;
    private javax.swing.JLabel jLFncGenDtContracao;
    private javax.swing.JLabel jLFncGenEndBairro;
    private javax.swing.JLabel jLFncGenEndCep;
    private javax.swing.JLabel jLFncGenEndCid;
    private javax.swing.JLabel jLFncGenEndComplemento;
    private javax.swing.JLabel jLFncGenEndEst;
    private javax.swing.JLabel jLFncGenEndLog;
    private javax.swing.JLabel jLFncGenEndNum;
    private javax.swing.JLabel jLFncGenEndRuaAv;
    private javax.swing.JLabel jLFncGenPesCPF;
    private javax.swing.JLabel jLFncGenPesDtNascimento;
    private javax.swing.JLabel jLFncGenPesEmail;
    private javax.swing.JLabel jLFncGenPesNome;
    private javax.swing.JLabel jLFncGenPesSexo;
    private javax.swing.JLabel jLFncGenSalario;
    private javax.swing.JLabel jLFncGenTelCodPais;
    private javax.swing.JLabel jLFncTelGenDDD;
    private javax.swing.JLabel jLFncTelGenTelNum;
    private javax.swing.JPanel jPFncGenBtnAdd;
    private javax.swing.JPanel jPFncGenBtnAtt;
    private javax.swing.JPanel jPFncGenBtnDel;
    private javax.swing.JPanel jPFncGenBtnFechar;
    private javax.swing.JPanel jPFncGenBtnSalvar;
    private javax.swing.JPanel jPFncGenBusca;
    private javax.swing.JPanel jPFncGenEndRH;
    private javax.swing.JPanel jPFncGenPesTel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFncGenBusca;
    private javax.swing.JTextField jTFncGenEndBairro;
    private javax.swing.JTextField jTFncGenEndCep;
    private javax.swing.JTextField jTFncGenEndComplemento;
    private javax.swing.JTextField jTFncGenEndNumero;
    private javax.swing.JTextField jTFncGenEndRuaAv;
    private javax.swing.JTextField jTFncGenPesCpf;
    private javax.swing.JTextField jTFncGenPesEmail;
    private javax.swing.JTextField jTFncGenPesNome;
    private javax.swing.JTextField jTFncGenSalario;
    private javax.swing.JTextField jTFncGenTelCodPais;
    private javax.swing.JTextField jTFncGenTelDDD;
    private javax.swing.JTextField jTFncGenTelNumero;
    // End of variables declaration//GEN-END:variables
}
