/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author joaop
 */
public class JPPdtGerenciamento extends javax.swing.JPanel {

    /**
     * Creates new form JPProduto2
     */
    public JPPdtGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPBtnPdtAdd = new javax.swing.JPanel();
        JBtnPdtAdd = new javax.swing.JButton();
        jPBtnPdtAtt = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPBtnPdtDel = new javax.swing.JPanel();
        JBtnPdtDel = new javax.swing.JButton();
        jPBtnPdtSalvar = new javax.swing.JPanel();
        JBtnPdtSalvar = new javax.swing.JButton();
        jPBtnPdtFechar = new javax.swing.JPanel();
        JBtnPdtFecharGeren = new javax.swing.JButton();
        jPPdtBusca = new javax.swing.JPanel();
        jCbPdtTipoBusca = new javax.swing.JComboBox<>();
        jTPdtBusca = new javax.swing.JTextField();
        jBtnPdtBuscar = new javax.swing.JButton();
        jPPdtInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTPdtNome = new javax.swing.JTextField();
        jTPdtQtdMin = new javax.swing.JTextField();
        jTPdtQtdMax = new javax.swing.JTextField();
        jCbPdtTipo = new javax.swing.JComboBox<>();
        jPPdtInfoEstoque = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLPdtEstCusto = new javax.swing.JLabel();
        jLEstQtdTotal = new javax.swing.JLabel();
        jLEstLote = new javax.swing.JLabel();
        jLEstDtValidade = new javax.swing.JLabel();
        jLEstFornecedor = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTEstQtdTotal = new javax.swing.JTextField();
        jTEstLote = new javax.swing.JTextField();
        jCbEstFornecedor = new javax.swing.JComboBox<>();
        jPBtnVoltar = new javax.swing.JPanel();
        JBtnPdtVoltar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPBtnPdtAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnPdtAdd.setText("Novo");

        javax.swing.GroupLayout jPBtnPdtAddLayout = new javax.swing.GroupLayout(jPBtnPdtAdd);
        jPBtnPdtAdd.setLayout(jPBtnPdtAddLayout);
        jPBtnPdtAddLayout.setHorizontalGroup(
            jPBtnPdtAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtAddLayout.setVerticalGroup(
            jPBtnPdtAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPdtAtt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("Atualizar");

        javax.swing.GroupLayout jPBtnPdtAttLayout = new javax.swing.GroupLayout(jPBtnPdtAtt);
        jPBtnPdtAtt.setLayout(jPBtnPdtAttLayout);
        jPBtnPdtAttLayout.setHorizontalGroup(
            jPBtnPdtAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtAttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtAttLayout.setVerticalGroup(
            jPBtnPdtAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBtnPdtAttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPdtDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnPdtDel.setText("Deletar");

        javax.swing.GroupLayout jPBtnPdtDelLayout = new javax.swing.GroupLayout(jPBtnPdtDel);
        jPBtnPdtDel.setLayout(jPBtnPdtDelLayout);
        jPBtnPdtDelLayout.setHorizontalGroup(
            jPBtnPdtDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtDel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtDelLayout.setVerticalGroup(
            jPBtnPdtDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtDel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPdtSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnPdtSalvar.setText("Salvar");

        javax.swing.GroupLayout jPBtnPdtSalvarLayout = new javax.swing.GroupLayout(jPBtnPdtSalvar);
        jPBtnPdtSalvar.setLayout(jPBtnPdtSalvarLayout);
        jPBtnPdtSalvarLayout.setHorizontalGroup(
            jPBtnPdtSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtSalvarLayout.setVerticalGroup(
            jPBtnPdtSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPdtFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnPdtFecharGeren.setText("Fechar");

        javax.swing.GroupLayout jPBtnPdtFecharLayout = new javax.swing.GroupLayout(jPBtnPdtFechar);
        jPBtnPdtFechar.setLayout(jPBtnPdtFecharLayout);
        jPBtnPdtFecharLayout.setHorizontalGroup(
            jPBtnPdtFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtFecharGeren, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtFecharLayout.setVerticalGroup(
            jPBtnPdtFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtFecharGeren, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPPdtBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCbPdtTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por Nome", "Busca por ID" }));

        jBtnPdtBuscar.setText("Buscar");

        javax.swing.GroupLayout jPPdtBuscaLayout = new javax.swing.GroupLayout(jPPdtBusca);
        jPPdtBusca.setLayout(jPPdtBuscaLayout);
        jPPdtBuscaLayout.setHorizontalGroup(
            jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbPdtTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPdtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPPdtBuscaLayout.setVerticalGroup(
            jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbPdtTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPdtBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPdtInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Informacoes sobre produto");

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade Mínima:");

        jLabel4.setText("Quantidade Máxima:");

        jLabel5.setText("Tipo de Produto:");

        jCbPdtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPPdtInfoLayout = new javax.swing.GroupLayout(jPPdtInfo);
        jPPdtInfo.setLayout(jPPdtInfoLayout);
        jPPdtInfoLayout.setHorizontalGroup(
            jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPPdtInfoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTPdtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPdtInfoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPdtQtdMin))
                    .addGroup(jPPdtInfoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPdtQtdMax))
                    .addGroup(jPPdtInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jCbPdtTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPPdtInfoLayout.setVerticalGroup(
            jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTPdtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTPdtQtdMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTPdtQtdMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCbPdtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPdtInfoEstoque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Estoque");

        jLabel7.setText("Data de Compra:");

        jLPdtEstCusto.setText("Custo:");

        jLEstQtdTotal.setText("Quantidade Total:");

        jLEstLote.setText("Lote:");

        jLEstDtValidade.setText("Data de Validade:");

        jLEstFornecedor.setText("Fornecedor:");

        jCbEstFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPPdtInfoEstoqueLayout = new javax.swing.GroupLayout(jPPdtInfoEstoque);
        jPPdtInfoEstoque.setLayout(jPPdtInfoEstoqueLayout);
        jPPdtInfoEstoqueLayout.setHorizontalGroup(
            jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                        .addComponent(jLPdtEstCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5))
                    .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                        .addComponent(jLEstQtdTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jTEstQtdTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                        .addComponent(jLEstLote)
                        .addGap(18, 18, 18)
                        .addComponent(jTEstLote))
                    .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                        .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLEstDtValidade))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                        .addComponent(jLEstFornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(jCbEstFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPPdtInfoEstoqueLayout.setVerticalGroup(
            jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtInfoEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPdtEstCusto)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstQtdTotal)
                    .addComponent(jTEstQtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstLote)
                    .addComponent(jTEstLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLEstDtValidade)
                .addGap(18, 18, 18)
                .addGroup(jPPdtInfoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstFornecedor)
                    .addComponent(jCbEstFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPBtnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBtnPdtVoltar.setText("Voltar");

        javax.swing.GroupLayout jPBtnVoltarLayout = new javax.swing.GroupLayout(jPBtnVoltar);
        jPBtnVoltar.setLayout(jPBtnVoltarLayout);
        jPBtnVoltarLayout.setHorizontalGroup(
            jPBtnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnVoltarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnVoltarLayout.setVerticalGroup(
            jPBtnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnVoltarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnPdtVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPdtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPBtnPdtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBtnPdtAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBtnPdtDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBtnPdtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBtnPdtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPPdtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPPdtInfoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBtnPdtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPBtnPdtDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPBtnPdtAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPBtnPdtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPBtnPdtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPBtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPPdtInfoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPPdtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnPdtAdd;
    private javax.swing.JButton JBtnPdtDel;
    private javax.swing.JButton JBtnPdtFecharGeren;
    private javax.swing.JButton JBtnPdtSalvar;
    private javax.swing.JButton JBtnPdtVoltar;
    private javax.swing.JButton jBtnPdtBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCbEstFornecedor;
    private javax.swing.JComboBox<String> jCbPdtTipo;
    private javax.swing.JComboBox<String> jCbPdtTipoBusca;
    private javax.swing.JLabel jLEstDtValidade;
    private javax.swing.JLabel jLEstFornecedor;
    private javax.swing.JLabel jLEstLote;
    private javax.swing.JLabel jLEstQtdTotal;
    private javax.swing.JLabel jLPdtEstCusto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPBtnPdtAdd;
    private javax.swing.JPanel jPBtnPdtAtt;
    private javax.swing.JPanel jPBtnPdtDel;
    private javax.swing.JPanel jPBtnPdtFechar;
    private javax.swing.JPanel jPBtnPdtSalvar;
    private javax.swing.JPanel jPBtnVoltar;
    private javax.swing.JPanel jPPdtBusca;
    private javax.swing.JPanel jPPdtInfo;
    private javax.swing.JPanel jPPdtInfoEstoque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTEstLote;
    private javax.swing.JTextField jTEstQtdTotal;
    private javax.swing.JTextField jTPdtBusca;
    private javax.swing.JTextField jTPdtNome;
    private javax.swing.JTextField jTPdtQtdMax;
    private javax.swing.JTextField jTPdtQtdMin;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
