/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author joaop
 */
public class JPPessoa extends javax.swing.JPanel {

    /**
     * Creates new form JPPessoa
     */
    public JPPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBtnPesGerenciar = new javax.swing.JPanel();
        jBtnPessoaGerenciar = new javax.swing.JButton();
        jPBtnPessoaFechar = new javax.swing.JPanel();
        jBtnPessoaFechar = new javax.swing.JButton();
        jPVendaBusca = new javax.swing.JPanel();
        jCbVendaTipoBusca = new javax.swing.JComboBox<>();
        jBtnVendaBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSpPessoaBusca = new javax.swing.JScrollPane();
        jTPessoa = new javax.swing.JTable();

        jPBtnPesGerenciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPessoaGerenciar.setText("Gerenciar");

        javax.swing.GroupLayout jPBtnPesGerenciarLayout = new javax.swing.GroupLayout(jPBtnPesGerenciar);
        jPBtnPesGerenciar.setLayout(jPBtnPesGerenciarLayout);
        jPBtnPesGerenciarLayout.setHorizontalGroup(
            jPBtnPesGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPesGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPessoaGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPesGerenciarLayout.setVerticalGroup(
            jPBtnPesGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBtnPesGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPessoaGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPessoaFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPessoaFechar.setText("Fechar");

        javax.swing.GroupLayout jPBtnPessoaFecharLayout = new javax.swing.GroupLayout(jPBtnPessoaFechar);
        jPBtnPessoaFechar.setLayout(jPBtnPessoaFecharLayout);
        jPBtnPessoaFecharLayout.setHorizontalGroup(
            jPBtnPessoaFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPessoaFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPessoaFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPessoaFecharLayout.setVerticalGroup(
            jPBtnPessoaFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPessoaFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPessoaFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPVendaBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCbVendaTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por CPF", "Busca por Nome" }));

        jBtnVendaBuscar.setText("Buscar");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPVendaBuscaLayout = new javax.swing.GroupLayout(jPVendaBusca);
        jPVendaBusca.setLayout(jPVendaBuscaLayout);
        jPVendaBuscaLayout.setHorizontalGroup(
            jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVendaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbVendaTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(jBtnVendaBuscar)
                .addContainerGap())
        );
        jPVendaBuscaLayout.setVerticalGroup(
            jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVendaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbVendaTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVendaBuscar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSpPessoaBusca.setViewportView(jTPessoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPVendaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPBtnPesGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBtnPessoaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpPessoaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBtnPessoaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBtnPesGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPVendaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpPessoaBusca)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPessoaFechar;
    private javax.swing.JButton jBtnPessoaGerenciar;
    private javax.swing.JButton jBtnVendaBuscar;
    private javax.swing.JComboBox<String> jCbVendaTipoBusca;
    private javax.swing.JPanel jPBtnPesGerenciar;
    private javax.swing.JPanel jPBtnPessoaFechar;
    private javax.swing.JPanel jPVendaBusca;
    private javax.swing.JScrollPane jSpPessoaBusca;
    private javax.swing.JTable jTPessoa;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
