/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author joaop
 */
public class JPProduto extends javax.swing.JPanel {

    /**
     * Creates new form JPProduto
     */
    public JPProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBtnPdtGerenciar = new javax.swing.JPanel();
        jBtnPdtGerenciar = new javax.swing.JButton();
        jPBtnPdtFechar = new javax.swing.JPanel();
        jBtnPdtFechar = new javax.swing.JButton();
        jPPdtBusca = new javax.swing.JPanel();
        jCPdtBuscaTipo = new javax.swing.JComboBox<>();
        jTPdtBusca = new javax.swing.JTextField();
        jBtnPdtBuscar = new javax.swing.JButton();
        jPTbPdtBusca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPdtBusca = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPBtnPdtGerenciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPdtGerenciar.setText("Gerenciar");
        jBtnPdtGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPdtGerenciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnPdtGerenciarLayout = new javax.swing.GroupLayout(jPBtnPdtGerenciar);
        jPBtnPdtGerenciar.setLayout(jPBtnPdtGerenciarLayout);
        jPBtnPdtGerenciarLayout.setHorizontalGroup(
            jPBtnPdtGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPdtGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtGerenciarLayout.setVerticalGroup(
            jPBtnPdtGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBtnPdtGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPdtGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnPdtFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPdtFechar.setText("Fechar");

        javax.swing.GroupLayout jPBtnPdtFecharLayout = new javax.swing.GroupLayout(jPBtnPdtFechar);
        jPBtnPdtFechar.setLayout(jPBtnPdtFecharLayout);
        jPBtnPdtFecharLayout.setHorizontalGroup(
            jPBtnPdtFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPdtFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnPdtFecharLayout.setVerticalGroup(
            jPBtnPdtFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnPdtFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnPdtFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPPdtBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCPdtBuscaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por Nome", "Busca por ID" }));

        jTPdtBusca.setText("jTextField1");

        jBtnPdtBuscar.setText("Buscar");

        javax.swing.GroupLayout jPPdtBuscaLayout = new javax.swing.GroupLayout(jPPdtBusca);
        jPPdtBusca.setLayout(jPPdtBuscaLayout);
        jPPdtBuscaLayout.setHorizontalGroup(
            jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPdtBuscaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPdtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPPdtBuscaLayout.setVerticalGroup(
            jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPdtBuscaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPdtBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPTbPdtBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTbPdtBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTbPdtBusca);

        javax.swing.GroupLayout jPTbPdtBuscaLayout = new javax.swing.GroupLayout(jPTbPdtBusca);
        jPTbPdtBusca.setLayout(jPTbPdtBuscaLayout);
        jPTbPdtBuscaLayout.setHorizontalGroup(
            jPTbPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTbPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPTbPdtBuscaLayout.setVerticalGroup(
            jPTbPdtBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTbPdtBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPdtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPBtnPdtGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBtnPdtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPTbPdtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBtnPdtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBtnPdtGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPPdtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPTbPdtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPdtGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPdtGerenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPdtGerenciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPdtBuscar;
    private javax.swing.JButton jBtnPdtFechar;
    private javax.swing.JButton jBtnPdtGerenciar;
    private javax.swing.JComboBox<String> jCPdtBuscaTipo;
    private javax.swing.JPanel jPBtnPdtFechar;
    private javax.swing.JPanel jPBtnPdtGerenciar;
    private javax.swing.JPanel jPPdtBusca;
    private javax.swing.JPanel jPTbPdtBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPdtBusca;
    private javax.swing.JTable jTbPdtBusca;
    // End of variables declaration//GEN-END:variables
}
