/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author joaop
 */
public class JPVenda extends javax.swing.JPanel {

    /**
     * Creates new form JPVenda
     */
    public JPVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBtnVendaGerenciar = new javax.swing.JPanel();
        jBtnVendaGerenciar = new javax.swing.JButton();
        jPBtnVendaFechar = new javax.swing.JPanel();
        jBtnVendaFechar = new javax.swing.JButton();
        jPVendaBusca = new javax.swing.JPanel();
        jCbVendaTipoBusca = new javax.swing.JComboBox<>();
        jBtnVendaBuscar = new javax.swing.JButton();
        jTVendaBusca = new javax.swing.JTextField();
        jSpVendaBusca = new javax.swing.JScrollPane();
        jTbVenda = new javax.swing.JTable();

        jPBtnVendaGerenciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnVendaGerenciar.setText("Gerenciar");

        javax.swing.GroupLayout jPBtnVendaGerenciarLayout = new javax.swing.GroupLayout(jPBtnVendaGerenciar);
        jPBtnVendaGerenciar.setLayout(jPBtnVendaGerenciarLayout);
        jPBtnVendaGerenciarLayout.setHorizontalGroup(
            jPBtnVendaGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnVendaGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnVendaGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnVendaGerenciarLayout.setVerticalGroup(
            jPBtnVendaGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnVendaGerenciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnVendaGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBtnVendaFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnVendaFechar.setText("Fechar");
        jBtnVendaFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendaFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnVendaFecharLayout = new javax.swing.GroupLayout(jPBtnVendaFechar);
        jPBtnVendaFechar.setLayout(jPBtnVendaFecharLayout);
        jPBtnVendaFecharLayout.setHorizontalGroup(
            jPBtnVendaFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnVendaFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnVendaFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBtnVendaFecharLayout.setVerticalGroup(
            jPBtnVendaFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBtnVendaFecharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnVendaFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPVendaBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCbVendaTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca por ID", "Busca por CPF", "Busca por Nome" }));

        jBtnVendaBuscar.setText("Buscar");

        jTVendaBusca.setText("jTextField1");

        javax.swing.GroupLayout jPVendaBuscaLayout = new javax.swing.GroupLayout(jPVendaBusca);
        jPVendaBusca.setLayout(jPVendaBuscaLayout);
        jPVendaBuscaLayout.setHorizontalGroup(
            jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVendaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbVendaTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTVendaBusca)
                .addGap(18, 18, 18)
                .addComponent(jBtnVendaBuscar)
                .addContainerGap())
        );
        jPVendaBuscaLayout.setVerticalGroup(
            jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVendaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPVendaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbVendaTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVendaBuscar)
                    .addComponent(jTVendaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Data", "Valor"
            }
        ));
        jSpVendaBusca.setViewportView(jTbVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPVendaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPBtnVendaGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPBtnVendaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpVendaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBtnVendaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBtnVendaGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPVendaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpVendaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVendaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendaFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnVendaFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVendaBuscar;
    private javax.swing.JButton jBtnVendaFechar;
    private javax.swing.JButton jBtnVendaGerenciar;
    private javax.swing.JComboBox<String> jCbVendaTipoBusca;
    private javax.swing.JPanel jPBtnVendaFechar;
    private javax.swing.JPanel jPBtnVendaGerenciar;
    private javax.swing.JPanel jPVendaBusca;
    private javax.swing.JScrollPane jSpVendaBusca;
    private javax.swing.JTextField jTVendaBusca;
    private javax.swing.JTable jTbVenda;
    // End of variables declaration//GEN-END:variables
}
